### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by KeishiNoguchi0702** [KeishiNoguchi0702/furima-35703#9]
## URL
https://furima-35703.herokuapp.com/

## Basic認証のIDとパスワード
- ID
 hoge
- PW
 hogehoge

## 出品者用のメールアドレスとパスワード
- メールアドレス
 hoge@hoge.com
- パスワード
 hoge1234

## 購入者用のメールアドレスとパスワード
- メールアドレス
 fuga@fuga.com
- パスワード
 fuga1234

**Comment by snkw-works** [comment]
@KeishiNoguchi0702 さん、大変お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態の出品者以外のユーザーのみ、必要な情報を適切に入力すると、商品の購入ができること**

- [ ] **クレジットカード決済ができること**

正しいカード情報を入力しても、エラーメッセージが表示され購入できません。
入力したカード情報
　カード番号　4242424242424242 
　CVC　     123 
　有効期限　  3月 23年

<img width="897" alt="スクリーンショット 2021-06-05 12 41 14" src="https://user-images.githubusercontent.com/54050089/120946979-4525af80-c779-11eb-8f41-d313212adb14.png">


※上記により、購入後の動作は次回ご提出時に確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by KeishiNoguchi0702** [comment]
確認とレビューありがとうございます！:smile:

修正完了しましたので、後ほど送りするフォームからご確認お願いいたします。

**Comment by takumi0530** [comment]
@KeishiNoguchi0702 さん、お待たせいたしました！ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/120954092-5d052f80-c789-11eb-9b79-74d4d356311a.png)
